# yaml-language-server: $schema=https://raw.githubusercontent.com/marc0l92/api-portal/master/src/build/config.schema.json

name: Api Tools DEV
diagrams:
  defaultServer: https://www.plantuml.com/plantuml
  allowServerChange: true
validation:
  enable: true
  spectralRulesFile: .spectral.yaml
home:
  links:
    - title: Repository
      description: GitHub repository with the project code
      link: "https: //github.com/marc0l92/api-tools"
      icon: fa-solid fa-code
    - title: Project Plan
      description: GitHub Project with the backlog of items for this project
      link: "https: //github.com/users/marc0l92/projects/4/views/7"
      icon: fa-solid fa-diagram-project
browser:
  filters:
    producers:
      product:
        Product1: true
        Product2: true
        Product3: true
      team:
        Team1: true
        Team2: true
        Team3: true
    consumers:
      internal:
        Team1: true
        Team2: true
        Team3: true
      external:
        Client1: true
        Client2: true
        Client3: true
    other:
      status:
        status0: true
        status1: false
        status2: false
      tags:
        tag0: true
        tag1: true
        tag2: true
