# yaml-language-server: $schema=https://raw.githubusercontent.com/marc0l92/api-portal/master/dist/buildConfig.schema.json

name: Api Portal DEV
diagrams:
  defaultServer: https://www.plantuml.com/plantuml
  allowServerChange: true
validation:
  enable: true
  spectralRulesFile: config/.spectral.yaml
home:
  links:
    - title: Repository
      description: GitHub repository with the project code
      link: "https: //github.com/marc0l92/api-portal"
      icon: fa-solid fa-code
    - title: Project Plan
      description: GitHub Project with the backlog of items for this project
      link: "https: //github.com/users/marc0l92/projects/4/views/7"
      icon: fa-solid fa-diagram-project
browser:
  filters:
    producers:
      product:
        tapy: false
        truckertools: false
      team:
        Team1: false
        Team2: false
        Team3: false
    consumers:
      internal:
        Team1: false
        Team2: false
        Team3: false
      external:
        Client1: false
        Client2: false
        Client3: false
    other:
      status:
        status0: false
        status1: false
        status2: false
      tags:
        tag0: false
        tag1: false
        tag2: false
