name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Build website
        run: |
          pnpm run build -- --configFile="./config.yaml"
      - name: Copy api examples
        run: |
          cp -r -f test/data/* inputApi
      - name: Generate api cache
        run: |
          pnpm run generate -- --configFile="./config.yaml"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com